name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ improved ]
  pull_request:
    branches: [ improved ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Store Unsigned APK files
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned APK Files
          path: app/build/outputs/apk/**/*.apk
      - name: Move APKs
        run: |
          mkdir apks
          mv app/build/outputs/apk/*/release/*.apk apks
      - name: ZipAlign & Sign APK
        uses: kevin-david/zipalign-sign-android-release@v2.0.1
        id: sign_app
        with:
          releaseDirectory: apks
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Store Signed APK files
        uses: actions/upload-artifact@v4
        with:
          name: Signed APK Files
          path: apks
